### ISSUE TITLE
Usage of a source directory other than `fnl/`

### ISSUE THREAD

**Issue by homedirectory** [rktjmp/hotpot.nvim#132]
Is the usage of a source directory for Fennel files other than the standard `fnl/` not supported properly?

Consider the following configuration (in `.hotpot.lua`):

```lua
return {
  build = {
    {verbose=true, atomic=true},
    { 'src/**/*.fnl', true },
  },
}
```

### Actual outcome

Lua files are generated in the same directory as their Fennel sources. 

### Expected outcome

Lua files are generated in the `lua` directory.
Ideally the destination directory for Lua files could be specified too.

**Comment by rktjmp** [comment]
This is by design, so paths like`{ftplugin/*.fnl, true}` works with minimal user setup, where the lua is expected to be a sibling. The `fnl/` dir is the special case.

https://github.com/rktjmp/hotpot.nvim/blob/87d2c346b940438388ec48e376f92d944fcb7efc/API.md?plain=1#L332-L334

You just need to swap `true` to a function that returns the path you want,

```lua
{ 'src/**/*.fnl', function(abs_path) return string.gsub(abs_path, "src/", "lua/", 1) end },
```

>  Ideally the destination directory for Lua files could be specified too.

https://github.com/rktjmp/hotpot.nvim/blob/87d2c346b940438388ec48e376f92d944fcb7efc/API.md?plain=1#L309-L312

When using .hotpot.lua the paths given to the function are (currently) always absolute paths.

**Comment by homedirectory** [comment]
@rktjmp I see, thank you for explaining. My bad on not reading the documentation carefully.
