### ISSUE TITLE
bug: compile error in unknown global in strict mode: vim

### ISSUE THREAD

**Issue by babygau** [rktjmp/hotpot.nvim#22]
I got this error whenever I open `nvim`. 

<img width="1045" alt="Screen Shot 2021-08-18 at 9 18 58 pm" src="https://user-images.githubusercontent.com/1514823/129889265-464d7837-3ca9-4c77-9f1f-9f462d7cde3f.png">

**Edit:** I just want to confirm that this bug doesn't happen with `aniseed` using the same `nvim config`

**Comment by rktjmp** [comment]
There was a bug fix in Fennel 0.10 that fixed a but with strict reporting, so that may be why you're seeing it in Hotpot, or Aniseed fiddles with the globals.

These might be related:

https://github.com/rktjmp/hotpot.nvim/issues/16
https://github.com/rktjmp/hotpot.nvim/issues/19

Are you using vim in a macro or just regular old fennel? I have no trouble accessing `vim` in "normal" code but macros are sandboxed by Fennel intentionally.

**Comment by babygau** [comment]
You're right. I got some `vim.*` in macros

**Comment by rktjmp** [comment]
Try `_G.vim`

**Comment by rktjmp** [comment]
`_G.vim` will still show a warning if you `nvimv 2> stderr.log`, but it is "non fatal" atm and you will only see the error when that module is being compiled.

I do plan to expose compiler configuration https://github.com/rktjmp/hotpot.nvim/issues/14 which will let you pass options to Fennels compiler to avoid this.

The reason I don't just set it up to allow `vim` by default (even though its not unreasonable to do since we're always in Vim) is that I want Hotpot to "just be Fennel", so it retains any defaults that come with it.

**Comment by babygau** [comment]
Thank you for details. IMO, it's worth to fix this, especially for new neovim users who want to use fennel for their config using `hotpot`. Apart from this, `hotpot` is working great for me 👍. Feel free to close this issue if you don't consider to fix it. Thank you!

**Comment by rktjmp** [comment]
Merged compiler options, see `:h hotpot-setup` or readme for configuration guide and the fennel lang site for options, or in my config I use:

```lua
  require("hotpot").setup({
    compiler = {
      macros = {
        env = "_COMPILER",
        compilerEnv = _G,
        allowedGlobals = false,
      }
    }
  })
```

Note you will still technically see errors in stderr until [this commit is released](https://git.sr.ht/~technomancy/fennel/commit/e461e244bd80d00262a0af1de95d4951061831fe) in the next fennel release.

**Comment by babygau** [comment]
Wow, that's great news. Thank you so much 😘
