### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by cpkio** [rktjmp/hotpot.nvim#25]
Does Hotpot support Windows? Are there any specific install instructions? Keeps complaining `hotpot.hotterpot` not found.

**Comment by alexaandru** [comment]
FWIW you can download legally and freely Windows images from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by rktjmp** [comment]
Yeah I did do a review at the time with a test in the disclosure https://github.com/rktjmp/hotpot.nvim/pull/32#issue-993210598

I think most of (all of?) the issues were basically when we do any "path patching" we expect it to be `/my-path`, not `\\my-path`, so any thing that expects to split on a `/` etc for "where do we put this" path generation fails. https://github.com/rktjmp/hotpot.nvim/pull/32#pullrequestreview-751435083 (more in "load items", somewhat out of date now but re-review should be pretty obvious.)

Ideally, I think all path generation and manipulation would be done unix style, since lua/luv translates that fine (and I assume any nvim functions would too since they would call out to them), but we can probably just replace any `api.nvim_get_runtime_path` calls (and anything else that asks for a path?) to something that translates windows paths to unix paths.

No idea if that is possible with non-c-drive paths, didn't check that. Might make that idea unreasonable. Maybe a little metatable type that tracks the drive and re-appends it on the way out or something.

But I will be honest, as a side project, to a side project, for an OS I dont use, where I have to mount stuff in a VM and use tools I don't like... My personal motivation is """low""". I'd rather spend the time on filling out the test suite (finally).

**Comment by alexaandru** [comment]
There is [package.config](https://www.lua.org/manual/5.3/manual.html#pdf-package.config) that can help with this. Although it seems to be available in 5.3 but not 5.1 (at least according to the docs), it seems to be available in Neovim. 

But yeah, I totally get the motivation part. I wasn't pushing for a fix on this :) I merely mentioned a tool I used to use, in case it would be useful, that's all. I'm not using Windows either.

Thanks again for all your great work, I absolutely love Fennel, it's so awesome to be able to use it in Neovim.

Cheers!

**Comment by rktjmp** [comment]
Beta support in #51

**Comment by rktjmp** [comment]
Fixed in #51 (probably?)

**Comment by cpkio** [comment]
Maybe I'm doing it wrong?

1. Clone `hotpot.nvim` to plugin folder. Nvim starts up fine, no errors.
2. Create a new plugin: `hot-test` folder with a `hot-test.fnl` inside. `hot-test.fnl` contains `(print "hello")` text.
3. `:lua require'hot-test'` results in

```
E5108: Error executing lua [string ":lua"]:1: module 'hot-test' not found:...-data\site\pack\user\start\hotpot.nvim/lua/hotpot/fs.lua:15: fs.write-file! io.open failed:R:\temp\nvim\hotpot\C\NvimLua\nvim-data\site\pack\user\start\hot-test\hot-test.lua
```

This happens because `…C\NvimLua\nvim-data\site\pack\user\start\hot-test\hot-test.lua` (created) is an empty directory, not a lua file.

**Comment by rktjmp** [comment]
Looks like you got caught in #53, try again! You'll have to manually remove that mistaken dir, felt that automating it might give someone a fright one day.

**Comment by cpkio** [comment]
It works now, nice 👍
