### ISSUE TITLE
`...` is nil from Fennel but not from Lua

### ISSUE THREAD

**Issue by datwaft** [rktjmp/hotpot.nvim#35]
Hello!

Today, while I was testing [utf.lua](https://github.com/Stepets/utf8.lua), a library that seems to promising to process regexes with utf-8 characters, I found a very strange bug related to hotpot.

When requiring the library from a fennel file the following error message is displayed:
```log
/root/.config/nvim/lua/utf8/init.lua:2: attempt to index local 'module_path' (a nil value)
```

It seems that this library aliases `...` as `module_path`, and when requiring a file from Fennel `...` is nil, but when requiring it from Lua it's not ([permalink](https://github.com/Stepets/utf8.lua/blob/17f4e009a22fb2f2e6ad316a05b2cca8e071fc3b/init.lua#L1-L2)).

```lua
local module_path = ...
module_path = module_path:match("^(.-)init$") or (module_path .. '.')
```

This could be related to those patches from #27.

This issue is strange because, as you can see in [this branch](https://github.com/datwaft/hotpot-issue_35/tree/success) of the reproduction repository, when requiring the module from `init.lua` there is no problem.

Additionally, as you can see in [this branch](https://github.com/datwaft/hotpot-issue_35/tree/change-order/config), when the order of the requires change and you first require from the Lua file and after that from the Fennel file, the test passes. This is because the package was successfully loaded from Lua and doesn't need to be loaded again.

This could be a temporary fix.

### How to reproduce

I created this repository to reproduce the issue using Docker: [datwaft/hotpot-issue_35](https://github.com/datwaft/hotpot-issue_35)

**Comment by rktjmp** [comment]
Fixed https://github.com/rktjmp/hotpot.nvim/commit/21622f3eb30017a635a15a44627fed7570735a9b

Probably fixes that cljlib `...` patch we needed too.

**Comment by datwaft** [comment]
Nice!

**Comment by rktjmp** [comment]
Hmm, seems that cljlib still needs the patch,

```fennel
; cljlib/init.fnl

(print ...)
(if (and ... (not= ... :init))
  (print :im (.. ... :.init-macros))
  (print :im :init-macros)) 

(import-macros {: defn : into : empty
                : when-let : if-let : when-some : if-some}
               (if (and ... (not= ... :init)) (.. ... :.init-macros) :init-macros))
```

Will still crash at the macro import, patching the macro path will work, and then the print checks for `...` look OK. Might need an rewrite of this, to behave like the lua loader (don't just eval?) 

https://github.com/rktjmp/hotpot.nvim/blob/21622f3eb30017a635a15a44627fed7570735a9b/fnl/hotpot/searcher/macro.fnl#L7-L24

**Comment by datwaft** [comment]
Thanks a lot for your effort!

**Comment by rktjmp** [comment]
Hmm, 

`fennel.eval` does accept a `...` after options, but it's not where the bug happens (will still be patched though).

If I 

```fennel
; cljlib/init.pnl
(eval-compiler
  (print ...))
````

I get

```
nil ~/.../cljlib/init.fnl
```

I _think_ the actual issue is that the process basically follows this:

1. require cljlib
2. compiler compiles cljlib/init.fnl -> lua
3. create loader for compiled  lua
4. run loader with modname as arg

The problem is that at step 2, the `import-macros` expression is evaluated _by the compiler_ , which does not have a module name set (`...` is `nil filename`). If it _could_ find the macro, then _inside_ the macro `...` would be set, and post-compile when we _run_ the module, `...` is also set. Basically that check just happens to fall into some no mans land, not quite a fennel context, not yet a lua context.

I had a look around the fennel source and couldn't immediately see a way to pass it in, I don't think the compiler has any concept of a "module" because it may be compiling chunks or whatever.

I think cljlib just makes some assumptions that if you're going to compile it, it's happening in the `cjllib/` dir or that otherwise you will eval it.

So cljlib probably will always need that patch.
