### ISSUE TITLE
`hotpot.lua:33: module 'hotpot.hotterpot' not found`

### ISSUE THREAD

**Issue by harrisonthorne** [rktjmp/hotpot.nvim#49]
Running into this issue after a full system upgrade (NixOS and home-manager). Issue doesn't seem to be related to neovim's version, as I didn't have this issue with both neovim 0.6 stable and 0.7 nightly before upgrading all packages in my environment.

Here's the messages I get immediately after starting neovim:

```
Error detected while processing /home/harrison/.config/nvim/init.vim:
line    5:
E5108: Error executing lua .../home-manager/start/vimplugin-hotpot.nvim/lua/hotpot.lua:33: module 'hotpot.hotterpot' not found:
	no field package.preload['hotpot.hotterpot']
	no file '/home/harrison/.cache/nvim/hotpot//nix/store/6gncbnhp95g4vr1504jsp6ffnr1ldizc-vimplugin-hotpot.nvim/fnl/hotpot/hotterpot.lua'
	no file '/nix/store/jxz9x9xp1ss6w06022c2dljjnhqqmck1-luajit-2.1.0-2021-10-27-env/share/lua/5.1/hotpot/hotterpot.lua'
	no file '/nix/store/jxz9x9xp1ss6w06022c2dljjnhqqmck1-luajit-2.1.0-2021-10-27-env/share/lua/5.1/hotpot/hotterpot/init.lua'
	no file '/nix/store/jxz9x9xp1ss6w06022c2dljjnhqqmck1-luajit-2.1.0-2021-10-27-env/lib/lua/5.1/hotpot/hotterpot.so'
	no file '/nix/store/jxz9x9xp1ss6w06022c2dljjnhqqmck1-luajit-2.1.0-2021-10-27-env/lib/lua/5.1/hotpot.so'
stack traceback:
	[C]: in function 'require'
	.../home-manager/start/vimplugin-hotpot.nvim/lua/hotpot.lua:33: in function <.../home-manager/start/vimplugin-hotpot.nvim/lua/hotpot.lua:29>
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk

# all of my fennel modules also not found ...

Error detected while processing /nix/store/6gncbnhp95g4vr1504jsp6ffnr1ldizc-vimplugin-hotpot.nvim/plugin/hotpot.vim:
line    2:
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'hotpot'
stack traceback:
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk
```

Here's my [neovim config](https://codeberg.org/harrisonthorne/dotfiles/src/branch/master/nvim) for home-manager as well. Its parent directory is the rest of my home-manager config.

Any ideas? Let me know if I can help at all :) Thanks!

**Comment by rktjmp** [comment]
Likely Hotpot thinks you have it compiled in cache but the cache has been deleted or moved.

Could you post a `tree` of `/home/harrison/.cache/nvim/hotpot`?

I would bet you have

```
hotpot/
  canary -> /some/path/to/hotpot/clone/canary/<checksum>
  /nix/store/<something-that-isn't-6gncbh...>
```

You can just delete the canary link or probably better off the whole hotpot folder in nvim's cache and it _should_ all start working again. I am interested to see the top level cache dir structure you have though.

Some context on why it's probably failing:

 Hotpot checks inside the cache root for a `canary` symlink. If it exists and resolves (i.e. the linked file exists too), it assumes that hotpot has been compiled to lua and is in cache and will try to load it.

When a new version of hotpot is pushed online/cloned down, the previous canary file is deleted (it's a checksum of the repo state, so each new version gets a new canary file). This means the link wont resolve and hotpot is _supposed_ to recompile itself.

I am betting that the canary file still exists, points to the current clone of your hotpot plugin (so hotpot doesn't think the compile is needed), but nix has swapped the contents of the cache so the require fails.


I don't have experience with nixOS/nix pm yet (on the todo list ...) so not 100% on all its internals but I assume when you bumped your config, the old config got deleted and the new one, since they're checksummed, doesn't match the old location.

Not sure if that is something I can reasonably handle with Hotpot. I guess it could do a one-time "canary existed but load failed, try compile" for these kinds of cases. Bit ugly though. Not sure if nix provides some "do this too" steps for when you upgrade, that could clear hotpots cache.

**Comment by harrisonthorne** [comment]
Here's the [tree](https://justpaste.it/8q3xp), seems like you're right! :)

Nix/home-manager *does* have [a way](https://github.com/nix-community/home-manager/pull/389) of running extra commands after a profile generation, so I will see if I can get that working and then report back here.

Thank you! 😁

**Comment by harrisonthorne** [comment]
Not a problem! Removing the cache definitely worked! Now to get Nix to do it automatically...

> Interesting that you seem to have lots of cache stores from each nix iteration but this is the first time you've seen the issue? Wonder what was different.

I think what was different was actually upgrading my packages/package registry on my system (via `home-manager switch --flake <flake_path> --recreate-lock-file`, as opposed to just `home-manager switch --flake <path>`)

> Though I guess nix is supposed to just let you roll back, theoretically?

Indeed! No need to apologize about the downtime :)

**Comment by harrisonthorne** [comment]
Update: Somebody on Reddit gave me a super helpful solution to the Nix issue. [Link to that.](https://www.reddit.com/r/NixOS/comments/rgaj3c/homemanager_how_to_run_a_command_remove_a/hojtyn6/?context=3)

Assuming this is just a NixOS-related issue, I will consider all the information here enough for a solution to the issue I was having. Thank you for the help, @rktjmp !

Love this plugin by the way! It's really cool. I hope you also have fun learning Nix if you get around to it. It's a joy to use 😁
