### ISSUE TITLE
Building fennel plugin with hotpot

### ISSUE THREAD

**Issue by shift-d** [rktjmp/hotpot.nvim#52]
I saw your paperplanes.nvim plugin and thought that it would be nice to try build my own fennel plugin. I tried to find a way to compile fnl directory into lua. I found #18 issue, but seems like it's closed without providing info whether it is implemented or not. After trying to copy build.fnl and hotpotfile.fnl i get an error about trying to index "f_out" variable which is not even being called inside those .fnl files. I hope you could explain any way to compile fennel plugins using hotpot.nvim

**Comment by rktjmp** [comment]
It's probably easiest to just use one file, call it `build.fnl` and copy most of the code out of [build.fnl](https://raw.githubusercontent.com/rktjmp/pact.nvim/master/build.fnl) from pact which has some code to [ignore compiling macro files](https://github.com/rktjmp/pact.nvim/blob/4e3de49eea4990c961f203c732c47f67c1914a10/build.fnl#L11).

```fnl
;; Copied
(local fennel ((. (require :hotpot.api.fennel) :latest)))
(local uv vim.loop)


(fn compile-file [in-path out-path]
  (if (not (string.match in-path "macros?%.fnl$"))
    (with-open [f-in (io.open in-path :r)
                f-out (io.open (string.gsub out-path ".fnl$" ".lua") :w)]
               (print :compile-file in-path :-> out-path)
               (local lines (fennel.compile-string (f-in:read "*a")))
               (f-out:write lines))))


(fn clone-file [in-path out-path]
  (with-open [f-in (io.open in-path :r)
              f-out (io.open out-path :w)]
             (print :clone-file in-path :-> out-path)
             (let [lines (f-in:read "*a")]
               (f-out:write lines))))


(fn handler-for [name]
  ; if lua file, just clone over
  ; if fnl file, compile out
  (match (string.match name "%.[%w]+$")
    nil (error (: "Could not find extension in %q" :format name))
    ".lua" clone-file
    ".fnl" compile-file
    any (error (: "Could not handle file type %q" :format any))))


(fn compile-dir [in-dir out-dir]
  (print :compile-dir in-dir :=> out-dir)
  ;; TODO: No checks for missing source dirs
  (let [scanner (uv.fs_scandir in-dir)]
    (var ok true)
    (each [name type #(uv.fs_scandir_next scanner) :until (not ok)]
      (match type
        "directory" (do
                      (local out-down (.. out-dir :/ name))
                      (local in-down (.. in-dir :/ name))
                      (vim.fn.mkdir out-down :p)
                      (compile-dir in-down out-down))
        "file" (let [in-file (.. in-dir :/ name)
                     out-file (.. out-dir :/ name)
                     handler (handler-for in-file)]
                (handler in-file out-file))))))
;; Added
(compile-dir :fnl :lua)
;; Open this file and run `:Fnlfile %` with hotpot installed
```

Then open `build.fnl` and run `:Fnlfile %` , you should see a bunch of compile `fnl -> lua` messages?

I closed that issue because it had been sitting stale for a long while and I wasn't sure if people would really care to use any builder, or if I still wanted to go the same direction with a separate file. I will re-think about it!

**Comment by shift-d** [comment]
It works, thanks! I will close this issue as you have answered my question
