### ISSUE TITLE
Compilation result differs from `macrodebug` result

### ISSUE THREAD

**Issue by datwaft** [rktjmp/hotpot.nvim#57]
# Hotpot Issue about Macro Expansion

This issue is about a difference between the result of a macro expansion in
`macrodebug` and the compilation result by using Hotpot.

## How to reproduce the issue

Clone the following repository: https://github.com/datwaft/hotpot-macro_expansion_issue

Execute the following Docker command:

```sh
docker build -t issue . && docker run -it issue
```

Inside the Docker container execute `nvim` to open Neovim, the result of
`macrodebug` will be printed and can be accessed using `:messages`.

When you open `/root/.cache/nvim/hotpot/root/.config/nvim/fnl/conf/init.lua`
the compilation result doesn't contain the underline as would be expected.

## Expected result

The macro...

```fennel
(highlight! MatchParen [:underline] {:bg "#262626"})
```

...should be expanded to:

```fennel
(vim.api.nvim_set_hl 0 "MatchParen" {:bg "#262626" :underline true})
```

## Current result

The macro...

```fennel
(highlight! MatchParen [:underline] {:bg "#262626"})
```

...is being expanded to:

```fennel
(vim.api.nvim_set_hl 0 "MatchParen" {:bg "#262626"})
```

**Comment by datwaft** [comment]
After a test this seems to be an issue with Fennel itself, so I will open a new issue on the Fennel repository.

**Comment by datwaft** [comment]
Here is the issue on the Fennel repository: https://github.com/bakpakin/Fennel/issues/425

**Comment by rktjmp** [comment]
https://todo.sr.ht/~technomancy/fennel/110 Related

**Comment by datwaft** [comment]
> https://todo.sr.ht/~technomancy/fennel/110 Related

Thanks! I will link it on the issue in the Fennel repository

**Comment by datwaft** [comment]
Nvm, you already liked it. Thanks!

**Comment by rktjmp** [comment]
I deleted that comment as I'm not tooooo sure how related they really are. That other issue was to do with re-evaluating macros repeatedly where as this seems to happen on the first call.

**Comment by rktjmp** [comment]
Gonna close this out as it's upstream and any fix will come through via (hopefully) the next Fennel release.

If a fix lands and you want to run a custom build before any release, you just have to replace `lua/hotpot/fennel.lua` with your own build and apply a tiny patch as shown here: https://github.com/rktjmp/hotpot.nvim/commit/a1b2775d9eaa6fb3dc607f7a136011478a738555 

Feel free to ping for help or if a new release happens and I don't notice.

**Comment by datwaft** [comment]
Thanks!

**Comment by datwaft** [comment]
Quick question related to this: does hotpot have any way to specify which version of Fennel to use?

The fix for this is already merged into the Fennel repo, but I can't use it yet with Hotpot.

**Comment by rktjmp** [comment]
(assuming non-nix env):

1) Build your own `fennel.lua` file
2) Drop it into `lua/hotpot/fennel.lua`
3) Edit `lua/hotpot/fennel.lua` and replicate this patch https://github.com/rktjmp/hotpot.nvim/commit/a1b2775d9eaa6fb3dc607f7a136011478a738555, the line numbers wont be the same but the surrounding context should be easy to find, it's inside `SPECIALS["require-macros"] = function...`.
4) Edit `lua/hotpot/searcher/module.lua` and find `versions = {"1.1.1"}` and replace it with `versions = {"1.2.0"}`

I have actually been thinking it would be nice to have a branch that automatically tracks fennel-head, so I will probably try rigging some CI for that some time.

Alternatively you can clone, update `deps/fennel.lua` link, patch the file, run `build.sh watch`, patch the version in the fennel and adjust your nvim plugin stuff to use your local clone. Probably no harder just to patch the first way though.

*Possibly* there could be a way to set a global flag before hotpot loads to instruct it to get fennel from not `hotpot.fennel` but you'd get compiler warnings because of the plugin version mismatch and I think 99% of the time people wouldn't need it (esp if there were an actual HEAD branch).

**Comment by datwaft** [comment]
Thank you!

**Comment by rktjmp** [comment]
*Theoretically* you can now track the [nightly](https://github.com/rktjmp/hotpot.nvim/tree/nightly) branch which *theoretically* should incorporate the latest upstream fennel each day (if there are any changes to merge).

The original idea was to run the test suite against any upcoming releases, you should be fine to just point your plugin manager at it but I can't promise I wont delete & recreate or rename the branch at some point. So I guess lock that fact away in your brain in case something explodes one day.

**Comment by datwaft** [comment]
Thank you! No problem with that, at least there is a way to manually patch it.
