### ISSUE TITLE
[FR] Plugin development template with Hotpot 

### ISSUE THREAD

**Issue by bangedorrunt** [rktjmp/hotpot.nvim#84]
It would be great where people could clone a Hotpot template repo so they can get their development up and running at ease. Aniseed already got this with embeded scripts and library.

**Comment by rktjmp** [comment]
It's a good idea, do you have ideas of what should be in it? I think it would really just be a `build.fnl` that called out to `hotpot.api.make`, and two empty `fnl` and `lua` dirs. Not sure if that's worth an extra repo but a "writing-plugins-with-fennel.md" should exist.

From what I remember, aniseed had a testing library too as well as frankly just needing more "setup" than a theoretical plugin built with hotpot would need.

There is some sticky decisions that depend on the developer, I personally gitignore `lua/*` so it doesn't show up in my file picker but that means I must remember to force add changed files, not sure I would want to force this on people.

Also since hotpot will always prefer things found in `lua/` (to be a good neighbour), you also need to dump that dir during dev (or rebuild all the time).

Indeed, even building out a `lua` folder isn't a technical requirement unless you don't want to force hotpot as a requirement (though in most cases you probably don't).

I will improve the documentation around this, not sure an actual repo would be a good fit or not, probably depends how complicated the docs get!

**Comment by monkoose** [comment]
> Yes, Aniseed has a testing library, here is my suggestion
> https://github.com/andreyorst/fennel-test

Not sure if i'm correct. But isn't this library test only fennel files? How much is it usable if you need to test some lua code inside neovim runtime?
Personally i would just go with plenary to test my lua code, not fennel code.

**Comment by rktjmp** [comment]
I've added a [plugin guide draft](https://github.com/rktjmp/hotpot.nvim/blob/master/WRITING-PLUGINS.md).

Hotpot wont provide a template as I don't believe setup is complex enough to warrant the extra work.
